name: admob_ads_manager
description: "This is a flutter plugin for google admob ads. This plugin is a wrapper for google mobile ads sdk."
version: 1.0.0
homepage:

environment:
  sdk: ^3.10.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
